# Generated by Django 3.0.4 on 2020-03-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user_id',
        ),
        migrations.AddField(
            model_name='todo',
            name='username',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
